server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbdemo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    tomcat:
      #该选项用来验证数据库连接的有效性。
      validation-query: SELECT 1
      #连接池的最大数据库连接数。设为0表示无限制。
      max-active: 100
      #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      max-wait: 10000
      #最大空闲数，数据库连接的最大空闲时间。默认100
      #超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
      max-idle: 100
      min-idle: 10
logging:
  path: E:/loger
  config: classpath:logback-spring.xml




