server:
  port: 8082
#  context-path: /hm
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.8:3306/healthdb??useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: java_web
    password: 1Y^CoMM%L$
    tomcat:
      #该选项用来验证数据库连接的有效性。
      validation-query: SELECT 1
      #连接池的最大数据库连接数。设为0表示无限制。
      max-active: 100
      #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      max-wait: 10000
      #最大空闲数，数据库连接的最大空闲时间。默认100
      #超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
      max-idle: 100
      min-idle: 10
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.3.64:3306/healthdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: luke


solrHost: http://58.215.80.185:8983/solr/hafcore

debugConfig.debug: 2

logging:
  path: /usr/local/healthmanager/logs
  config: classpath:logback-spring.xml
#  path: D:/logger





